# Generated by Django 5.2.12 on 2026-03-10 01:59

import django.utils.timezone
import pedidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('muito_urgente', 'Muito urgente')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('aguardando_arquivo', 'Aguardando arquivo/ideia'), ('orcamento', 'Orçamento'), ('fabricacao', 'Fabricação'), ('acabamento', 'Acabamento'), ('pronto', 'Pronto'), ('entregue', 'Entregue')], default='aguardando_arquivo', max_length=30)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=pedidos.models.pedido_upload_path)),
                ('observacoes_internas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
